conn lab
    keyexchange=ikev1
    aggressive=yes
    type=tunnel
    authby=psk
    left=%defaultroute
    leftid=@east
    leftsubnet=10.10.2.1/32
    right=172.28.0.1
    rightid=@west
    rightsubnet=10.10.1.1/32
    ike=des-md5-modp1024!
    esp=3des-md5-modp1024!
    forceencaps=yes
    ikelifetime=1h
    lifetime=30m
    rekey=no
    keyingtries=%forever
    dpdaction=restart
    dpddelay=30s
    auto=add
