conn lab
    keyexchange=ikev2
    type=tunnel
    authby=psk
    left=%defaultroute
    leftid=@west
    leftsubnet=10.10.1.1/32
    right=172.28.0.2
    rightid=@east
    rightsubnet=10.10.2.1/32
    ike=aes256gcm16-prfsha256-modp2048!
    esp=aes256gcm16-modp2048!
    forceencaps=yes
    ikelifetime=1h
    lifetime=30m
    rekey=no
    keyingtries=%forever
    dpdaction=restart
    dpddelay=30s
    auto=add
